name: telegirc_server
description: A Telegram to IRC server
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.1.0
  sqlite3: ^1.4.0
  uuid: ^3.0.5
  tdlib_types:
    git: 
      url: https://github.com/dancojocaru2000/dart_tdlib_types
  stack_trace: ^1.10.0
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
